### ISSUE TITLE
[Fabric] Fabric Issue Template Test

### ISSUE THREAD

**Issue by ZandercraftGames** [MeowMC/Door-Knocker#4]
**Describe The Bug**

This is just a test of the Fabric template.

**To Reproduce**

**Expected Behavior**

No issues.

**Screenshots**

None.

**Operating System:**
 - OS: Windows
 - Version: 10

**Versioning Info:**
 - Mod Version: 1.0.
 - Fabric Version: thing
 - Fabric API Version (If applicable): n/a
 - Optifine Version (If applicable): n/a
- Optimization Mods (i.e. Sodium, Phosphor, etc.): n/a

**Additional context**

Stuffs

**Other mods:**

 - Mod 1
 - Mod 2
 - Mod 3

**Comment by froyo4u** [comment]
Damn you closed that fast

**Comment by ZandercraftGames** [comment]
> Damn you closed that fast

🤣
